#!/usr/bin/php
<?php

const APACHE_SITES_DIR = "/etc/apache2/sites-available";
const APACHE_WEB_DIR = "/var/www";
const HOSTS_FILE = "/etc/hosts";
const LOCAL_IP = "127.0.1.1";

if (!is_writable(APACHE_SITES_DIR) || !is_writable(APACHE_WEB_DIR) || !is_writable(HOSTS_FILE)) {
    echo "This script does not enough permissions. Run it as sudo\n";
} else {
    $domain = readline("Enter domain of the virtual host: ");
    $local = readline("Local (will add to hosts file)(y/n): ");

    $conf_filename = "$domain.conf";
    $document_root = APACHE_WEB_DIR . '/$domain/public';

    echo "\nCreating VirtualHost $domain.....\n......\n";
    $conf =
        <<<CONF
<VirtualHost *:80>
	ServerName $domain

	ServerAdmin webmaster@$domain
	DocumentRoot $document_root

	ErrorLog \${APACHE_LOG_DIR}/$domain.error.log
	CustomLog \${APACHE_LOG_DIR}/$domain.access.log combined
</VirtualHost>

CONF;

    if ($local == 'y') {
        $ip = LOCAL_IP;
        $write = fopen(HOSTS_FILE, 'a');

        $host_content =
            <<<HOST
#added by virtual.php
$ip $domain

HOST;

        fwrite($write, $host_content);
        fclose($write);
    } else {

        $configure_www = readline("\nDo you want to setup www redirect to non-www(y/n)");
        if ($configure_www == "y") {
            echo "\nRedirecting www to non-www.....\n";
            echo "Remember to add a CNAME in dns records for www.$domain to $domain\n";

            $conf .=
                <<<CONF
		
<VirtualHost *:80>
	ServerName www.$domain
	Redirect permanent / http://$domain
</VirtualHost>
CONF;
        }
    }

    $conf_path = APACHE_SITES_DIR . "/$conf_filename";

    $write = fopen($conf_path, "w");
    fwrite($write, $conf);
    fclose($write);

    if (!mkdir($document_root, 0755, true)) {
        echo "The document root: $document_root was not created. Create it yourself.\n";
    } else {
        $write = fopen($document_root . "/index.html", "w");
        fwrite($write, "VirtualHost $domain is working!!");
        fclose($write);
    }

    echo "\n.........................\n.........................\n.........................";
    echo "\nVirtualHost $domain is ready. Run a2ensite $domain to enable.\n";
    echo "Test virtual host by visiting $domain/ in your browser after enabling.\n";

}

